name: main

on:
  pull_request:
  merge_group:

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: "22"
          exclude-regex: 'bazel/registry'

  test:
    name: Build & Test (Linux, Cross-Compile Windows & macOS)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      
      - name: Build and Test on Linux
        run: |
          bazelisk build //... --platforms=@llvm//platforms:linux_x86_64
          ./test/test.sh
      
      - name: Cross-compile for Windows
        run: bazelisk build //... --platforms=@llvm//platforms:windows_x86_64

      - name: Cross-compile for macOS (x86_64)
        run: bazelisk build //... --platforms=@llvm//platforms:macos_x86_64

      - name: Cross-compile for macOS (arm64)
        run: bazelisk build //... --platforms=@llvm//platforms:macos_aarch64
