name: main

on:
  release:
    types: [published]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jidicula/clang-format-action@v4.9.0
        with: { clang-format-version: "16" }

  release-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            /Users/runneradmin/AppData/Local/bazelisk
            /Users/runneradmin/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v4
      - run: curl -fL https://github.com/bazelbuild/buildtools/releases/download/v6.3.3/buildozer-windows-amd64.exe -o .\buildozer.exe
      - run: bazelisk --bazelrc=.github/ci.bazelrc build //...
      - run: cp .\bazel-bin\bzlmod\bzlmod.exe .\bzlmod-windows-amd64.exe && cp .\bazel-bin\bzlreg\bzlreg.exe .\bzlreg-windows-amd64.exe 
      - run: gh release upload ${{ github.event.release.tag_name }} bzlmod-windows-amd64.exe bzlreg-windows-amd64.exe 
        env:
          GH_TOKEN: ${{ github.token }}

  release-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: sudo curl -fL https://github.com/bazelbuild/buildtools/releases/download/v6.3.3/buildozer-linux-amd64 -o /usr/bin/buildozer && sudo chmod +x /usr/bin/buildozer
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v4
      - run: bazelisk --bazelrc=.github/ci.bazelrc build //...
      - run: cp ./bazel-bin/bzlmod/bzlmod ./bzlmod-linux-amd64 && cp ./bazel-bin/bzlreg/bzlreg ./bzlreg-linux-amd64
      - run: gh release upload ${{ github.event.release.tag_name }} bzlmod-linux-amd64 bzlreg-linux-amd64
        env:
          GH_TOKEN: ${{ github.token }}
